/*****************************************************************************
 * Source code information
 * -----------------------
 * Original author    Myriam Leggieri
 * Author email       myriam.leggieri@gmail.com
 * Package            @package@
 * Web site           @website@
 * Created            20 Aug 2009 03:34
 * Filename           $RCSfile $
 * Revision           $Revision$
 * Release status     @releaseStatus@ $State: Exp $
 *
 * Last modified on   $Date: 2009/06/05 11:46:00 $
 *               by   $Author: myriam $
 *
 * @copyright@
 *****************************************************************************/

// Package
///////////////////////////////////////
package org.hackystat.linkedservicedata.vocabularies;

// Imports
///////////////////////////////////////
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;

/**
 * Vocabulary definitions from
 * /home/myrtill/Hackystat_linkedData/mysqlProva/workspace/hackystat-linked
 * -service-data/src/org/hackystat/linkedservicedata/vocabularies/hackystat.rdf
 *
 * @author Auto-generated by schemagen on 20 Aug 2009 03:34
 */
public class HackystatVocab {
  /**
   * <p>
   * The ontology model that holds the vocabulary terms
   * </p>
   */
  public static OntModel m_model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM, null);

  /**
   * <p>
   * The namespace of the vocabulary as a string
   * </p>
   */
  public static final String NS = "http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/";

  /**
   * <p>
   * The namespace of the vocabulary as a string
   * </p>
   *
   * @see #NS
   */
  public static String getURI() {
    return NS;
  }

  /**
   * <p>
   * The namespace of the vocabulary as a resource
   * </p>
   */
  public static final Resource NAMESPACE = m_model.createResource(NS);

  /** PREFIX. */
  public static final String PREFIX = "hacky";

  // Vocabulary properties
  // /////////////////////////

  public static final ObjectProperty AMOUNT_OF_CODE_ISSUES = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/amountOfCodeIssues");

  public static final ObjectProperty AVERAGE_VALUE = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/averageValue");

  public static final ObjectProperty BUILD_QUALITY = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/buildQuality");

  public static final ObjectProperty CLOSED_TIME = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/closedTime");

  public static final ObjectProperty COMMIT_FREQUENCY = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/commitFrequency");

  public static final ObjectProperty COVERAGE_QUALITY = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/coverageQuality");

  public static final ObjectProperty DEVELOPER = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/developer");

  public static final ObjectProperty DEVELOPMENT_TIME = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/developmentTime");

  public static final ObjectProperty DOCUMENTER = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/documenter");

  public static final ObjectProperty HAS_PARAMETER = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/hasParameter");

  public static final ObjectProperty HAS_RESULT = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/hasResult");

  public static final ObjectProperty HELPER = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/helper");

  public static final ObjectProperty INCLUDES_PHASE = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/includesPhase");

  public static final ObjectProperty KNOWS = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/knows");

  public static final ObjectProperty MAINTAINER = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/maintainer");

  public static final ObjectProperty MODIFIED_TIME = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/modifiedTime");

  public static final ObjectProperty OPENED_TIME = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/openedTime");

  public static final ObjectProperty PRIVACY_LEVEL = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/privacyLevel");

  public static final ObjectProperty PROJECT_OWNER = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/projectOwner");

  public static final ObjectProperty TESTER = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/tester");

  public static final ObjectProperty TRANSLATOR = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/translator");

  public static final ObjectProperty UNIT_TEST_QUALITY = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/unitTestQuality");

  public static final ObjectProperty USES_TOOL = m_model
      .createObjectProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/usesTool");

  public static final OntProperty AUTHOR = m_model
      .createOntProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/author");

  public static final OntProperty COMMUNICATION_EFFORT = m_model
      .createOntProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/communicationEffort");

  public static final OntProperty COULD_CAUSES = m_model
      .createOntProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/couldCauses");

  public static final OntProperty ENDED = m_model
      .createOntProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/ended");

  public static final OntProperty INVITATED = m_model
      .createOntProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/invitated");

  public static final OntProperty INVOLVED_USER = m_model
      .createOntProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/involvedUser");

  public static final OntProperty MEMBER = m_model
      .createOntProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/member");

  public static final OntProperty MODIFIED = m_model
      .createOntProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/modified");

  public static final OntProperty ON_MACHINE = m_model
      .createOntProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/onMachine");

  public static final OntProperty ON_OPERATING_SYSTEM = m_model
      .createOntProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/onOperatingSystem");

  public static final OntProperty PRECEEDS = m_model
      .createOntProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/preceeds");

  public static final OntProperty PROJECT = m_model
      .createOntProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/project");

  public static final OntProperty SPECTATOR = m_model
      .createOntProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/spectator");

  public static final OntProperty KARMA = m_model
  .createOntProperty("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/karma");

  // Vocabulary classes
  // /////////////////////////

  public static final OntClass CLEANNESS = m_model
      .createClass("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/Cleanness");

  public static final OntClass CODE_QUALITY = m_model
      .createClass("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/CodeQuality");

  public static final OntClass COMMAND = m_model
      .createClass("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/Command");

  public static final OntClass DEVELOPER_CLASS = m_model
      .createClass("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/Developer");

  public static final OntClass DEVELOPMENT_PHASE = m_model
      .createClass("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/DevelopmentPhase");

  public static final OntClass KNOWLEDGE = m_model
      .createClass("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/Knowledge");

  public static final OntClass MACHINE = m_model
      .createClass("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/Machine");

  public static final OntClass OPERATING_SYSTEM = m_model
      .createClass("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/OperatingSystem");

  public static final OntClass PROGRAMMING_LANGUAGE = m_model
      .createClass("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/ProgrammingLanguage");

  public static final OntClass PROJECT_MANAGER = m_model
      .createClass("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/ProjectManager");

  public static final OntClass REVIEW = m_model
      .createClass("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/Review");

  public static final OntClass REVIEWER = m_model
      .createClass("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/Reviewer");

  public static final OntClass STRENGHT = m_model
      .createClass("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/Strenght");

  public static final OntClass TOOL = m_model
      .createClass("http://dasha.ics.hawaii.edu:9875/linkedservicedata/vocab/Tool");

  // Vocabulary individuals
  // /////////////////////////

}

/*
 * @footer@
 */

