/*****************************************************************************
 * Source code information
 * -----------------------
 * Original author    Myriam Leggieri
 * Author email       myriam.leggieri@gmail.com
 * Package            @package@
 * Web site           @website@
 * Created            18 Jun 2009 22:34
 * Filename           $RCSfile $
 * Revision           $Revision$
 * Release status     @releaseStatus@ $State: Exp $
 *
 * Last modified on   $Date: 2009/06/05 11:46:00 $
 *               by   $Author: myriam $
 *
 * @copyright@
 *****************************************************************************/

// Package
///////////////////////////////////////
package org.hackystat.linkedservicedata.vocabularies;

// Imports
///////////////////////////////////////
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;

/**
 * Vocabulary definitions from
 * /home/myrtill/Hackystat_linkedData/mysqlProva/workspace/hackystat-linked
 * -service-data/src/org/hackystat/linkedservicedata/vocabularies/iswc.daml
 *
 * @author Auto-generated by schemagen on 18 Jun 2009 22:34
 */
public class IswcVocab {
  /**
   * <p>
   * The ontology model that holds the vocabulary terms
   * </p>
   */
  private static OntModel m_model = ModelFactory.createOntologyModel(OntModelSpec.DAML_MEM, null);

  /**
   * <p>
   * The namespace of the vocabulary as a string
   * </p>
   */
  public static final String NS = "http://annotation.semanticweb.org/iswc/iswc.daml#";

  public static final String PREFIX = "iswc";

  /**
   * <p>
   * The namespace of the vocabulary as a string
   * </p>
   *
   * @see #NS
   */
  public static String getURI() {
    return NS;
  }

  /**
   * <p>
   * The namespace of the vocabulary as a resource
   * </p>
   */
  public static final Resource NAMESPACE = m_model.createResource(NS);

  // Vocabulary properties
  // /////////////////////////

  public static final ObjectProperty ALGORITHM = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#algorithm");

  public static final ObjectProperty APPLICATION = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#application");

  public static final ObjectProperty APPLICATION_DOMAIN = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#application_domain");

  public static final ObjectProperty AUTHOR = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#author");

  public static final ObjectProperty CONFERENCE = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#conference");

  public static final ObjectProperty FORMAL_LANGUAGE = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#formal_language");

  public static final ObjectProperty FUNDING_BY = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#funding_by");

  public static final ObjectProperty HAS_SUBTOPIC = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#hasSubtopic");

  public static final ObjectProperty HAS_AFFILIATE = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#has_affiliate");

  public static final ObjectProperty HAS_AFFILIATION = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#has_affiliation");

  public static final ObjectProperty INVOLVED_IN_PROJECT = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#involved_in_project");

  public static final ObjectProperty IS_ABOUT = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#is_about");

  public static final ObjectProperty METHOD = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#method");

  public static final ObjectProperty ORGANIZATIONS_INVOLVED = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#organizations_involved");

  public static final ObjectProperty PERSONS_INVOLVED = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#persons_involved");

  public static final ObjectProperty RESEARCH_TOPICS = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#research_topics");

  public static final ObjectProperty TOOL = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#tool");

  public static final ObjectProperty TOPIC = m_model
      .createObjectProperty("http://annotation.semanticweb.org/iswc/iswc.daml#topic");

  public static final DatatypeProperty ADDRESS = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#address");

  public static final DatatypeProperty COUNTRY = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#country");

  public static final DatatypeProperty DATE = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#date");

  public static final DatatypeProperty EMAIL = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#email");

  public static final DatatypeProperty EVENT_TITLE = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#eventTitle");

  public static final DatatypeProperty FAX = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#fax");

  public static final DatatypeProperty FIRST_NAME = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#first_Name");

  public static final DatatypeProperty HOMEPAGE = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#homepage");

  public static final DatatypeProperty LAST_NAME = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#last_Name");

  public static final DatatypeProperty LOCATION = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#location");

  public static final DatatypeProperty MIDDLE_INITIAL = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#middle_Initial");

  public static final DatatypeProperty NAME = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#name");

  public static final DatatypeProperty PHONE = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#phone");

  public static final DatatypeProperty PHOTO = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#photo");

  public static final DatatypeProperty PROJECT_TITLE = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#project_title");

  public static final DatatypeProperty TITLE = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#title");

  public static final DatatypeProperty YEAR = m_model
      .createDatatypeProperty("http://annotation.semanticweb.org/iswc/iswc.daml#year");

  // Vocabulary classes
  // /////////////////////////

  public static final OntClass PERSON = m_model
      .createClass("http://annotation.semanticweb.org/iswc/iswc.daml#Person");

}