/*****************************************************************************
 * Source code information
 * -----------------------
 * Original author    Myriam Leggieri
 * Author email       myriam.leggieri@gmail.com
 * Package            @package@
 * Web site           @website@
 * Created            16 Jun 2009 14:49
 * Filename           $RCSfile $
 * Revision           $Revision$
 * Release status     @releaseStatus@ $State: Exp $
 *
 * Last modified on   $Date: 2009/06/05 11:46:00 $
 *               by   $Author: myriam $
 *
 * @copyright@
 *****************************************************************************/

// Package
///////////////////////////////////////
package org.hackystat.linkedservicedata.vocabularies;

import com.hp.hpl.jena.ontology.OntClass;
import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.hp.hpl.jena.ontology.OntProperty;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;

// Imports
///////////////////////////////////////

/**
 * Vocabulary definitions from
 * /home/myrtill/Hackystat_linkedData/mysqlProva/workspace/hackystat-linked
 * -service-data/src/org/hackystat/linkedservicedata/vocabularies/vom.owl
 *
 * @author Auto-generated by schemagen on 16 Jun 2009 14:49
 */
public class VomVocab {
  /**
   * <p>
   * The ontology model that holds the vocabulary terms
   * </p>
   */
  public static OntModel m_model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM, null);

  /**
   * <p>
   * The namespace of the vocabulary as a string
   * </p>
   */
  public static final String NS = "http://www.ifi.uzh.ch/ddis/evoont/2008/11/vom#";

  /** prefix. */
  public static final String PREFIX = "vom";

  /**
   * <p>
   * The namespace of the vocabulary as a string
   * </p>
   *
   * @see #NS
   */
  public static String getURI() {
    return NS;
  }

  /**
   * <p>
   * The namespace of the vocabulary as a resource
   * </p>
   */
  public static final Resource NAMESPACE = m_model.createResource(NS);

  /**
   *
   */
  public static boolean isModelSet = false;

  /**
   *
   */
  public static void setModel() {
    m_model.setNsPrefix("evoOnt", "http://www.ifi.uzh.ch/ddis/evoont/2008/11/vom/vom.owl");
    // it should read a dataset and not a schema
    // m_model.read("http://www.ifi.uzh.ch/ddis/evoont/2008/11/vom/vom.owl");
    isModelSet = true;
  }

  /** Vocabulary properties. */
  public static final OntProperty HAS_VERSION = m_model.createOntProperty(NS + "hasVersion");

  /** Vocabulary classes. */
  public static final OntClass VERSION = m_model.createClass(NS + "Version");

}