/*****************************************************************************
 * Source code information
 * -----------------------
 * Original author    Myriam Leggieri
 * Author email       myriam.leggieri@gmail.com
 * Package            @package@
 * Web site           @website@
 * Created            21 Aug 2009 11:58
 * Filename           $RCSfile $
 * Revision           $Revision$
 * Release status     @releaseStatus@ $State: Exp $
 *
 * Last modified on   $Date: 2009/06/05 11:46:00 $
 *               by   $Author: myriam $
 *
 * @copyright@
 *****************************************************************************/


// Package
///////////////////////////////////////
package org.hackystat.linkedservicedata.vocabularies;


// Imports
///////////////////////////////////////
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;




/**
 * Vocabulary definitions from /home/myrtill/Hackystat_linkedData/mysqlProva/workspace/hackystat-linked-service-data/src/org/hackystat/linkedservicedata/vocabularies/commontag.rdf
 * @author Auto-generated by schemagen on 21 Aug 2009 11:58
 */
public class CommontagVocab {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );

    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://commontag.org/ns#";

    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}

    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );

    public static final String PREFIX = "commontag";




    // Vocabulary properties
    ///////////////////////////

    /** <p>A resource (URI) representing the concepts described by the content.</p> */
    public static final OntProperty IS_ABOUT = m_model.createOntProperty( "http://commontag.org/ns#isAbout" );

    /** <p>A local, human-readable name for a Tag.</p> */
    public static final OntProperty LABEL = m_model.createOntProperty( "http://commontag.org/ns#label" );

    /** <p>A a resource (URI) representing the conceptual meaning of a Tag.</p> */
    public static final OntProperty MEANS = m_model.createOntProperty( "http://commontag.org/ns#means" );

    /** <p>Links a resource to a Common Tag.</p> */
    public static final OntProperty TAGGED = m_model.createOntProperty( "http://commontag.org/ns#tagged" );

    /** <p>The date the Tag was assigned.</p> */
    public static final OntProperty TAGGING_DATE = m_model.createOntProperty( "http://commontag.org/ns#taggingDate" );


    // Vocabulary classes
    ///////////////////////////


    // Vocabulary individuals
    ///////////////////////////

}

/*
@footer@
*/

