/*****************************************************************************
 * Source code information
 * -----------------------
 * Original author    Myriam Leggieri
 * Author email       myriam.leggieri@gmail.com
 * Package            @package@
 * Web site           @website@
 * Created            02 Aug 2009 18:29
 * Filename           $RCSfile $
 * Revision           $Revision$
 * Release status     @releaseStatus@ $State: Exp $
 *
 * Last modified on   $Date: 2009/06/05 11:46:00 $
 *               by   $Author: myriam $
 *
 * @copyright@
 *****************************************************************************/

// Package
///////////////////////////////////////
package org.hackystat.linkedservicedata.vocabularies;

// Imports
///////////////////////////////////////
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;

/**
 * Vocabulary definitions from
 * /home/myrtill/Hackystat_linkedData/mysqlProva/workspace/hackystat-linked
 * -service-data/src/org/hackystat/linkedservicedata/vocabularies/helios_bt.owl
 *
 * @author Auto-generated by schemagen on 02 Aug 2009 18:29
 */
public class Helios_btVocab {
  /**
   * <p>
   * The ontology model that holds the vocabulary terms
   * </p>
   */
  private static OntModel m_model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM, null);

  /**
   * <p>
   * The namespace of the vocabulary as a string
   * </p>
   */
  public static final String NS = "http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#";

  public static final String PREFIX = "helios";

  /**
   * <p>
   * The namespace of the vocabulary as a string
   * </p>
   *
   * @see #NS
   */
  public static String getURI() {
    return NS;
  }

  /**
   * <p>
   * The namespace of the vocabulary as a resource
   * </p>
   */
  public static final Resource NAMESPACE = m_model.createResource(NS);

  // Vocabulary properties
  // /////////////////////////

  /**
   * <p>
   * A bugtracker of a project
   * </p>
   */
  public static final ObjectProperty BUGTRACKER = m_model
      .createObjectProperty("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#bugtracker");

  public static final ObjectProperty BUGTRACKER_VERSION = m_model
      .createObjectProperty("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#bugtrackerVersion");

  /**
   * <p>
   * Adding the inverse link between bom:Issue and bom:Component, which was described in the evoont
   * diagram.
   * </p>
   */
  public static final ObjectProperty HAS_ISSUE = m_model
      .createObjectProperty("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#hasIssue");

  /**
   * <p>
   * An Issue/Task can have subIssues / subTasks, in particular to model the Bug - Task relations in
   * LaunchPad
   * </p>
   */
  public static final ObjectProperty HAS_SUB_ISSUE = m_model
      .createObjectProperty("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#hasSubIssue");

  /**
   * <p>
   * An issue is present in a bugtracker
   * </p>
   */
  public static final ObjectProperty IN_BUGTRACKER = m_model
      .createObjectProperty("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#inBugtracker");

  /**
   * <p>
   * An Issue is a duplicate of another Issue, and it should be "closed", only having its duplicate
   * stay open. In principle, there should be a restriction here on the state and resolution of that
   * Issue (resolution == duplicate)
   * </p>
   */
  public static final ObjectProperty IS_DUPLICATE_OF = m_model
      .createObjectProperty("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#isDuplicateOf");

  public static final ObjectProperty IS_IN_PRODUCT = m_model
      .createObjectProperty("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#isInProduct");

  public static final ObjectProperty IS_MERGED_INTO = m_model
      .createObjectProperty("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#isMergedInto");

  /**
   * <p>
   * An Issue can be reported in many different projects / distributions (see LaunchPad's also
   * affects relations)
   * </p>
   */
  public static final ObjectProperty REPORTED_ALSO_IN = m_model
      .createObjectProperty("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#reportedAlsoIn");

  /**
   * <p>
   * A particular case of reportedAlsoIn relation when it affects bugs in a distribution package and
   * its corresponding upstream project's bug (see forwarded-to link in debbugs)
   * </p>
   */
  public static final ObjectProperty REPORTED_UPSTREAM_IN = m_model
      .createObjectProperty("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#reportedUpstreamIn");

  public static final DatatypeProperty BUG_TRACKER_URL = m_model
      .createDatatypeProperty("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#bugTrackerURL");

  // Vocabulary classes
  // /////////////////////////

  public static final OntClass BUG_TRACKER = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugTracker");

  public static final OntClass BUGZILLA_DEFECT = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaDefect");

  public static final OntClass BUGZILLA_ENHANCEMENT = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaEnhancement");

  /**
   * <p>
   * Complements the Priority class by adding Bugzilla specific subclass.
   * </p>
   */
  public static final OntClass BUGZILLA_PRIORITY_P1 = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaPriorityP1");

  /**
   * <p>
   * Complements the Priority class by adding Bugzilla specific subclass.
   * </p>
   */
  public static final OntClass BUGZILLA_PRIORITY_P2 = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaPriorityP2");

  /**
   * <p>
   * Complements the Priority class by adding Bugzilla specific subclass.
   * </p>
   */
  public static final OntClass BUGZILLA_PRIORITY_P3 = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaPriorityP3");

  /**
   * <p>
   * Complements the Priority class by adding Bugzilla specific subclass.
   * </p>
   */
  public static final OntClass BUGZILLA_PRIORITY_P4 = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaPriorityP4");

  /**
   * <p>
   * Complements the Priority class by adding Bugzilla specific subclass.
   * </p>
   */
  public static final OntClass BUGZILLA_PRIORITY_P5 = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaPriorityP5");

  /**
   * <p>
   * Complements the Resolution class by adding Bugzilla specific subclass.
   * </p>
   */
  public static final OntClass BUGZILLA_RESOLUTION_DUPLICATE = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaResolutionDUPLICATE");

  /**
   * <p>
   * Complements the Resolution class by adding Bugzilla specific subclass.
   * </p>
   */
  public static final OntClass BUGZILLA_RESOLUTION_FIXED = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaResolutionFIXED");

  /**
   * <p>
   * Complements the Resolution class by adding Bugzilla specific subclass.
   * </p>
   */
  public static final OntClass BUGZILLA_RESOLUTION_INVALID = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaResolutionINVALID");

  /**
   * <p>
   * Complements the Resolution class by adding Bugzilla specific subclass.
   * </p>
   */
  public static final OntClass BUGZILLA_RESOLUTION_MOVED = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaResolutionMOVED");

  /**
   * <p>
   * Complements the Resolution class by adding Bugzilla specific subclass.
   * </p>
   */
  public static final OntClass BUGZILLA_RESOLUTION_WONTFIX = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaResolutionWONTFIX");

  /**
   * <p>
   * Complements the Resolution class by adding Bugzilla specific subclass.
   * </p>
   */
  public static final OntClass BUGZILLA_RESOLUTION_WORKSFORME = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaResolutionWORKSFORME");

  public static final OntClass BUGZILLA_SEVERITYBLOCKER = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaSeverityblocker");

  public static final OntClass BUGZILLA_SEVERITYCRITICAL = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaSeveritycritical");

  public static final OntClass BUGZILLA_SEVERITYENHANCEMENT = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaSeverityenhancement");

  public static final OntClass BUGZILLA_SEVERITYMAJOR = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaSeveritymajor");

  public static final OntClass BUGZILLA_SEVERITYMINOR = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaSeverityminor");

  public static final OntClass BUGZILLA_SEVERITYNORMAL = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaSeveritynormal");

  public static final OntClass BUGZILLA_SEVERITYTRIVIAL = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaSeveritytrivial");

  public static final OntClass BUGZILLA_STATE_ASSIGNED = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaStateASSIGNED");

  public static final OntClass BUGZILLA_STATE_CLOSED = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaStateCLOSED");

  public static final OntClass BUGZILLA_STATE_NEW = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaStateNEW");

  public static final OntClass BUGZILLA_STATE_REOPENED = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaStateREOPENED");

  public static final OntClass BUGZILLA_STATE_RESOLVED = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaStateRESOLVED");

  public static final OntClass BUGZILLA_STATE_UNCONFIRMED = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaStateUNCONFIRMED");

  public static final OntClass BUGZILLA_STATE_VERIFIED = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#BugzillaStateVERIFIED");

  public static final OntClass DEBBUGS_DEFECT = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#DebbugsDefect");

  /**
   * <p>
   * Enhancements for wishlists
   * </p>
   */
  public static final OntClass DEBBUGS_ENHANCEMENT = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#DebbugsEnhancement");

  public static final OntClass DEBBUGS_SEVERITYCRITICAL = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#DebbugsSeveritycritical");

  public static final OntClass DEBBUGS_SEVERITYGRAVE = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#DebbugsSeveritygrave");

  public static final OntClass DEBBUGS_SEVERITYIMPORTANT = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#DebbugsSeverityimportant");

  public static final OntClass DEBBUGS_SEVERITYMINOR = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#DebbugsSeverityminor");

  public static final OntClass DEBBUGS_SEVERITYNORMAL = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#DebbugsSeveritynormal");

  public static final OntClass DEBBUGS_SEVERITYSERIOUS = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#DebbugsSeverityserious");

  public static final OntClass DEBBUGS_SEVERITYWISHLIST = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#DebbugsSeveritywishlist");

  /**
   * <p>
   * Only state in UDD bugs.status that we'll consider terminal
   * </p>
   */
  public static final OntClass DEBBUGS_STATEDONE = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#DebbugsStatedone");

  public static final OntClass DEBBUGS_STATEFIXED = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#DebbugsStatefixed");

  public static final OntClass DEBBUGS_STATEFORWARDED = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#DebbugsStateforwarded");

  public static final OntClass DEBBUGS_STATEPENDING = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#DebbugsStatepending");

  public static final OntClass DEBBUGS_STATEPENDING_FIXED = m_model
      .createClass("http://picoforge.int-evry.fr/projects/svn/helios_wp3/2009/07/helios_bt.owl#DebbugsStatepending-fixed");

  // Vocabulary individuals
  // /////////////////////////

}

/*
 * @footer@
 */

